### ISSUE TITLE
How to add new objects without using Create buttons?

### ISSUE THREAD

**Issue by lopis** [bergie/create#214]
I'm creating some objects in javascript that I want to enable edition with Create. Create doesn't seem to provide a way to manually add new objects. Right now I'm restarting Create altogether but this seems overkill and some information is lost. Is it possible to make Create recognize my new element as editable?

**Comment by bergie** [comment]
@lopis you can simply register them to VIE's main Backbone collection.

Example: https://github.com/bergie/create/blob/00d43ea4e53ea084333f0280753964db9131ade5/src/metadataWidgets/jquery.Midgard.midgardTags.js#L85
