### ISSUE TITLE
Allow specifying an editor config for multiple RDF property names at once

### ISSUE THREAD

**Issue by flack** [bergie/create#62]
Scenario: There are multiple editable properties on an HTML page. About half of them are supposed to accept only plaintext (like a person's or company's name or a blog entry's title) and the other half can also accept HTML-formatted input and images (like the text of a blog post, or the biography of a person).

In the current createjs configuration format, I will have to provide an editor configuration foreach RDF property name, so f.x. one for dcterms:title, one for foaf:name and so on, which leads to much redundancy. It would be much nicer if there was a way to specify one configuration called "Plaintext" and another one called "Richtext" and assign them to the properties of your choosing.

**Comment by iJungleboy** [comment]
I'm trying to work with this - but it doesn't seem to work. 
1. setEditorForContentType seems to have the identical code like setEditorForProperty
2. basically if I set typeof on any node containing editable data it immediately becomes un-editable
